##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-backgrounds
    - autopoint
    - git
    - libglib2.0-dev
    - make
    - mate-common
    - meson

build_scripts:
  - ./make-scanbuild
