##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-backgrounds
    - autopoint
    - git
    - libglib2.0-dev
    - make
    - mate-common
    - meson

build_scripts:
  - ./autogen.sh
  - ./configure
  - make

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -         bash ./debian.sh
  -     fi
  -     make distcheck
  - fi
