##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-backgrounds
    - aptitude
    - autopoint
    - clang-tools
    - expect #required for unbuffer
    - git
    - libglib2.0-dev
    - make
    - cafe-common
    - meson

build_scripts:
  - ./make-scanbuild
