AC_PREREQ(2.62)

AC_INIT([cafe-backgrounds], [1.25.0], [http://www.cafe-desktop.org])

AM_INIT_AUTOMAKE([1.11 foreign no-dist-gzip dist-xz tar-ustar check-news])

AM_SILENT_RULES([yes])

AM_GNU_GETTEXT_VERSION([0.19.8])
AM_GNU_GETTEXT([external])

AM_MAINTAINER_MODE

AC_CONFIG_FILES([
Makefile
abstract/Makefile
desktop/Makefile
nature/Makefile
po/Makefile.in
])

AC_OUTPUT
